name: Deploy Student Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy application
        run: |
          cd /home/bhavyasree/student-projects
          git fetch origin main
          git reset --hard origin/main
          docker compose up -d --build
          docker compose ps